@isTest
private class SlashclockHelpCommandTest {

    /**
     * /clock help
     */
    @isTest
    private static void clockHelp() {
        System.assert(false, 'TODO');
    }

    /**
     * /clock help in
     */
    @isTest
    private static void clockHelpIn() {
        System.assert(false, 'TODO');
    }

    /**
     * /clock help out
     */
    @isTest
    private static void clockHelpOut() {
        System.assert(false, 'TODO');
    }

    /**
     * /clock help report
     */
    @isTest
    private static void clockHelpReport() {
        System.assert(false, 'TODO');
    }

    /**
     * /clock help slice
     */
    @isTest
    private static void clockHelpSlice() {
        System.assert(false, 'TODO');
    }

    /**
     * /clock help entries
     */
    @isTest
    private static void clockHelpEntries() {
        System.assert(false, 'TODO');
    }

    /**
     * /clock help strike
     */
    @isTest
    private static void clockHelpStrike() {
        System.assert(false, 'TODO');
    }
}