/**
 * This test class provides functional validation for United States West Coast
 * users, making sure that all commands work correctly in the context
 * of the "America/Los_Angeles" time zone.
 */
@isTest
private class SlashclockLosAngelesTest {

    @isTest
    private static void clockInAsNewUser() {
        System.assert(false, 'TODO');
    }

    @isTest
    private static void clockIn() {
        System.assert(false, 'TODO');
    }

    @isTest
    private static void clockOut() {
        System.assert(false, 'TODO');
    }

    @isTest
    private static void clockReport() {
        System.assert(false, 'TODO');
    }

    @isTest
    private static void clockEntries() {
        System.assert(false, 'TODO');
    }

    @isTest
    private static void clockInFromNewTimeZone() {
        System.assert(false, 'TODO');
    }

    @isTest
    private static void clockOutFromNewTimeZone() {
        System.assert(false, 'TODO');
    }

    @isTest
    private static void clockReportFromDifferentTimeZone() {
        System.assert(false, 'TODO');
    }
}